#!/bin/bash

# Slack webhook URL

SLACK_WEBHOOK_URL="https://app.whistleit.io/api/webhooks/64d1f8fc602e1e5d893bc8>

# Send congratulatory message

curl -X POST -H 'Content-type: application/json' --data '{"text":"Congratulatio>
